[package]
name = "carece-de-nome"
version = "0.1.0"
authors = ["Vinícius Miguel <lemao.vrm07@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.8.3", feature = "std_rng" }

[dependencies.tetra]
version = "0.6.3"
default-features = false
features = ['texture_png', 'texture_jpeg', 'texture_gif', 'texture_bmp']

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
